# Generated by Django 4.1.5 on 2023-02-15 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_avatar_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='avatar',
        ),
    ]
