# Generated by Django 4.1.5 on 2023-03-03 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('recipe', 'desc')},
        ),
    ]
