# Generated by Django 4.1.5 on 2023-02-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeimage',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
