# Generated by Django 4.1.5 on 2023-01-25 17:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Recipe Category', 'verbose_name_plural': 'Recipe Categories'},
        ),
        migrations.AlterModelOptions(
            name='recipereview',
            options={'ordering': ('-date_added',)},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='categories',
        ),
        migrations.AlterField(
            model_name='recipereview',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RecipeLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='categories',
            field=models.ForeignKey(default=datetime.datetime(2023, 1, 25, 17, 33, 15, 580748, tzinfo=datetime.timezone.utc), on_delete=models.SET(recipes.models.get_default_recipe_category), related_name='recipes', to='recipes.category'),
            preserve_default=False,
        ),
    ]
