# Generated by Django 4.1.5 on 2023-01-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipeingredient_quantity_as_float_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
