# Generated by Django 4.1.5 on 2023-02-10 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeimage',
            name='recipe',
        ),
    ]
