# Generated by Django 4.1.5 on 2023-03-10 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230310_0038'),
    ]

    operations = [
    ]
