# Generated by Django 4.1.5 on 2023-03-09 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230309_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='serving',
            field=models.CharField(blank=True, default='4', max_length=100),
            preserve_default=False,
        ),
    ]
