# Generated by Django 4.1.5 on 2023-01-31 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_recipe_sources_source_recipe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instruction',
            new_name='Directions',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='recipereview',
            options={'ordering': ('-date_added',), 'verbose_name_plural': 'Reviews'},
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='notes',
        ),
        migrations.AddField(
            model_name='recipe',
            name='notes',
            field=models.CharField(blank=True, max_length=500, verbose_name='Recipe|notes'),
        ),
        migrations.DeleteModel(
            name='RecipeLike',
        ),
    ]
