# Generated by Django 4.1.5 on 2023-02-27 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipereview_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipereview',
            unique_together=set(),
        ),
    ]
