# Generated by Django 4.1.5 on 2023-01-20 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipeingredient_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='quantity_as_float',
        ),
    ]
