# Generated by Django 4.1.5 on 2023-02-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_recipeimage_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='notes',
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(blank=True, verbose_name='Recipe|instruction'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
