# Generated by Django 4.1.5 on 2023-01-31 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_instruction_directions_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Directions',
            new_name='Direction',
        ),
    ]
