# Generated by Django 4.1.5 on 2023-03-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230303_1139'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='heading',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='title',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='recipereview',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('recipe', 'title')},
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='desc',
        ),
    ]
