# Generated by Django 4.1.5 on 2023-03-11 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_main_image'),
        ('recipes', '0004_auto_20230310_0849'),
    ]

    operations = [
    ]
