# Generated by Django 4.1.5 on 2023-01-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_recipeingredient_quantity_as_float'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
    ]
