# Generated by Django 4.1.5 on 2023-01-31 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0005_rename_directions_direction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Direction',
            new_name='Instruction',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Recipe Category', 'verbose_name_plural': 'Recipe Categories'},
        ),
        migrations.AlterModelOptions(
            name='recipereview',
            options={'ordering': ('-date_added',)},
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='notes',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RecipeLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
