# Generated by Django 4.1.5 on 2023-02-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_rename_direction_instruction_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='quantity_as_float',
        ),
    ]
