# Generated by Django 4.1.5 on 2023-02-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('appetizers', 'Appetizers'), ('bread', 'Bread'), ('breakfast', 'Breakfast'), ('desserts', 'Desserts'), ('vegan', 'Vegan'), ('drink', 'Drink'), ('main dish', 'Maindish'), ('salad', 'Salad'), ('soups, stew and chill ', 'Soups'), ('side dish', 'Sidedish'), ('marinades and sauces', 'Marinades')], max_length=50),
        ),
    ]
