# Generated by Django 4.1.5 on 2023-02-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_remove_recipeingredient_quantity_as_float'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='source',
            field=models.CharField(max_length=20, null=True, verbose_name='Source|url'),
        ),
        migrations.AlterField(
            model_name='recipereview',
            name='stars',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='RecipeLike',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
