# Generated by Django 4.1.5 on 2023-01-24 16:10

import datetime
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_remove_recipe_category_recipe_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='serve',
            new_name='rating_count',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='is_active',
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(default=datetime.datetime(2023, 1, 24, 16, 10, 57, 498359, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='categories',
            field=models.ManyToManyField(to='recipes.category'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='rating_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='serving',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Maximum 120 characters', max_length=120, unique=True),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='recipes_rec_search__ce256b_gin'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['slug'], name='recipes_rec_slug_412256_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['rating_value'], name='recipes_rec_rating__e43bcc_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['rating_count'], name='recipes_rec_rating__66f33e_idx'),
        ),
    ]
