# Generated by Django 4.1.5 on 2023-02-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_remove_source_recipe_recipe_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='source',
            field=models.CharField(max_length=200, null=True, verbose_name='Source|url'),
        ),
    ]
