# Generated by Django 4.1.5 on 2023-03-09 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_ingredient_recipe'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('recipe', 'title')},
        ),
    ]
