# Generated by Django 4.1.5 on 2023-02-02 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipe_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='method',
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='step_number',
        ),
        migrations.AddField(
            model_name='instruction',
            name='direction',
            field=models.TextField(blank=True, verbose_name='Recipe|direction'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruction', to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', related_query_name='recipe', to='recipes.recipe'),
        ),
    ]
