# Generated by Django 4.1.5 on 2023-01-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Source|url')),
                ('url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Source',
                'verbose_name_plural': 'Sources',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='sources',
            field=models.ManyToManyField(blank=True, to='recipes.source'),
        ),
    ]
