# Generated by Django 4.1.5 on 2023-02-07 14:28

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0011_rename_categories_recipe_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(on_delete=models.SET(recipes.models.get_default_recipe_category), related_name='recipe_list', to='recipes.category'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='Image/recipe'),
        ),
        migrations.AlterField(
            model_name='recipereview',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='recipereview',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to=settings.AUTH_USER_MODEL),
        ),
    ]
