# Generated by Django 4.1.5 on 2023-02-06 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0011_rename_categories_recipe_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipereview',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='recipereview',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to=settings.AUTH_USER_MODEL),
        ),
    ]
