# Generated by Django 4.1.5 on 2023-02-07 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_recipe_category_alter_recipe_image_and_more'),
        ('recipes', '0012_alter_recipereview_recipe_alter_recipereview_user'),
    ]

    operations = [
    ]
